name: heroku_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: Base structure for a Slack bot server running on Heroku.
dependencies:
  http: ^0.11.3+3
  logging: ^0.11.2
  shelf: ^0.6.5
  shelf_route: ^0.14.1
